# Generated by Django 3.0.5 on 2020-07-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemAndCart', '0003_auto_20200727_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
